### PR TITLE
feat: add support for VPC flow logs [DEVOP-500]

### PR DESCRIPTION
**Pull request by jai**
### Description

* Renames the wrapper module file to be clearer
* Adds a PR template
* Adds support for enabling [AWS VPC flow logs](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html)

---
This change is [Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-vpc/3)

### CODE REVIEW

**Review by pgcloud — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-vpc/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @theerasan)

**Review by theerasan — APPROVED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-vpc/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jai)

**Review by theerasan — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-vpc/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jai)

**Review by theerasan — APPROVED** [review]
> Reviewed 6 of 8 files at r4, 2 of 2 files at r5, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-vpc/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jai)

**Pull request merged**
